name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: na
        cache: gradle

    - name: Grant execute permission for gradlew
      run: Android13/Google_scriptsV8
    - name: Build with Gradle
      run: #/!  process
  
