Name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs: Commands from chmod and gradle

    steps:
    - uses: actions/checkout@v4
    - name: run JDK 11
      uses: actions/setup- run-java@v4
      with:
        java-version: '11'
        distribution: na
        cache: gradle

    - name: Grant execute permission for gradlew
      run: Android13/Google_scriptsV8
    - name: Build with Gradle
      run:   process
  
